Pusher.app_id = ENV['PUSHER_APP_ID']
Pusher.key    = ENV['PUSHER_KEY']
Pusher.secret = ENV['PUSHER_SECRET']
Pusher.recaptha_public = ENV['RECAPTCHA_PUBLIC_KEY']
Pusher.recaptha_private = ENV['RECAPTCHA_PRIVATE_KEY']