# Add application configuration variables here, as shown below.
#
AWS_ACCESS_KEY_ID: AKIAIWCJ4LTYBFVANAPQ
AWS_SECRET_ACCESS_KEY: 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
GOOGLE_MAPS_KEY: AIzaSyBDFNoSaQVXBLpNlGkYF6rmNZHsXtt1N44