
development:
  adapter: postgresql
  database: reservester_development
  pool: 5
  timeout: 5000
  username: JuanAnMN
  password:
  host: localhost

test:
  adapter: postgresql
  database: reservester_development
  pool: 5
  timeout: 5000
  username: JuanAnMN
  password:
  host: localhost
