development:
  adapter: sqlite3
  database: reservester_development
  username: huge
  password: 
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: reservester_test
  username: huge
  password: 
  pool: 5
  timeout: 5000

